global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'flask-app'
    static_configs:
      - targets: ['backend:5000']
  - job_name: "frontend-metrics"
    static_configs:
      - targets: [ "frontend-metrics:3001" ]
  - job_name: 'cadvisor'
    static_configs:
      - targets: [ 'cadvisor:8080' ]